# Generated by Django 5.1.3 on 2024-11-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
